module.exports = {
    friendlyName: "Connect user",

    description: "Update the appToken of the connected user",

    inputs: {
        id: {
            description: 'The id of the user to connect',
            type: 'string',
            required: true
        },
        appToken: {
            description: 'The token generated by the android app',
            type: 'ref',
            required: true
        }

    },

    exits: {
        success: {
            responseType: 'json',
        }
    },

    fn: async function (inputs, exits) {
        await sails.helpers.user.updateUser.with(inputs);

        return exits.success();
    }
};